# Generated by Django 3.2.15 on 2022-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA', '0004_commentnbavideo_nbavideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
