# Generated by Django 3.2.15 on 2022-10-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20221009_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='user',
        ),
    ]
