# Generated by Django 3.2.15 on 2022-10-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_remove_uploadvideo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
