# Generated by Django 3.2.15 on 2022-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20221031_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
