# Generated by Django 3.2.15 on 2022-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20221102_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
