# Generated by Django 3.2.15 on 2022-11-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0014_alter_uploadvideo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='user',
        ),
    ]
