# Generated by Django 3.2.15 on 2022-11-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_uploadvideo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadvideo',
            name='imagename',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
