# Generated by Django 3.2.15 on 2022-11-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_uploadvideo_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='videoname',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
