# Generated by Django 3.2.15 on 2022-11-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0019_alter_uploadvideo_videoname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
