# Generated by Django 3.2.15 on 2022-12-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0022_alter_tweet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweets.comment'),
        ),
    ]
