# Generated by Django 3.2.15 on 2022-12-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0023_comment_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_reply',
            new_name='total_comments',
        ),
    ]
