# Generated by Django 3.2.15 on 2022-12-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0024_rename_comment_reply_comment_total_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='total_comments',
        ),
        migrations.CreateModel(
            name='TotalComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweets.comment')),
            ],
        ),
    ]
