# Generated by Django 3.2.15 on 2022-12-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0025_auto_20221203_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tweets.comment'),
        ),
        migrations.DeleteModel(
            name='TotalComments',
        ),
    ]
