# Generated by Django 3.2.15 on 2022-12-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0027_auto_20221203_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCommets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_comments', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.comment')),
            ],
        ),
    ]
