# Generated by Django 3.2.15 on 2022-12-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0028_countcommets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountCommets',
        ),
    ]
